### ISSUE TITLE
Inconsistent item number and label missing

### ISSUE THREAD

**Issue by zelo2** [hezy18/Z-SV#1]
Dear authors:
I hope all is well. 
Thanks for providing an impressive short video recommendation dataset with EEG data. However, I found there are two issues whchi may need to be solved:
1) After I merged the json files of user behavior, I found there are 2684 items in the dataset, which is inconsistent with 2636 items in the original paper.
2) Some Visual and Auditory scores are missing. For example, in the file "01_behavior_MAES.json", this user's ratings towards item "0" in terms of Visual and Auditory are missing.

Looking forward to your reply.
Sincerely,
2024.11.25

**Comment by hezy18** [comment]
Dear Sir or Madam,
Thank you for your valuable feedback on the EEG-SVRec dataset. We truly appreciate your interest and careful examination of the dataset.

Regarding the two issues you mentioned:

1. **Item Quantity Discrepancy**: You are correct that there is a discrepancy between the number of items reported in the original paper (2636 items) and the number of items in the current dataset (2684 items). The final version of the dataset contains 2684 items (with item IDs ranging from 0 to 2683).

2. **Missing Visual and Auditory Scores**: Some user behavior files' missing ratings for Visual and Auditory scores are due to incomplete annotations in certain user studies. As noted in the paper, Figure 4 in the paper shows the statistics for the available annotations.

We have updated EEG's DE features, and you can re-download the revised version. Also, we have provided additional explanations in the GitHub repository to help clear up these issues.

If you have any further questions or encounter any additional issues, please do not hesitate to reach out. 

Best regards,
Zhiyu He

**Comment by zelo2** [comment]
Thank you for your kind reply. I have no further questions about the dataset. This work is really impressive.
